_target_: banda.models.configs.BandsplitModuleConfig

# Bandsplit Configuration
band_specs:
  _target_: banda.models.spectral.get_bandsplit_specs_factory
  bandsplit_type: musical # Changed to string value
  n_bands: 64 # Removed n_fft and fs here
require_no_overlap: False
require_no_gap: True
normalize_channel_independently: False
treat_channel_as_feature: True