losses:
- cls: L1SNRLossCapSilenceContrib
  name: l1snr-time
  weight: 1.0
  params:
    domain: "audio"
    eps: 1e-3
    max_silence_contrib: 0.1
    silence_thresh_db: -60

- cls: L1SNRLossCapSilenceContrib
  name: l1snr-tf
  weight: 1.0
  params:
    domain: "spectrogram"
    eps: 1e-3
    max_silence_contrib: 0.1
    silence_thresh_db: -60

- cls: L1SNRLossCapSilenceContrib
  name: l1snr-tf-1k
  weight: 1.0
  params:
    n_fft: 1024
    domain: "spectrogram/1024"
    eps: 1e-3
    max_silence_contrib: 0.1
    silence_thresh_db: -60

- cls: L1SNRLossCapSilenceContrib
  name: l1snr-tf-512
  weight: 1.0
  params:
    n_fft: 512
    domain: "spectrogram/512"
    eps: 1e-3
    max_silence_contrib: 0.1
    silence_thresh_db: -60

# - cls: DecibelMatchLoss
#   name: dbm
#   weight: 0.1
#   params:
#     eps: 1e-6
#     adaptive: true
#     min_weight: 0.1
#     max_weight: 1.0
#     min_db: -60
#     max_below_true: 12
