name: banda
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - pytorch
  - pytorch-lightning
  - hydra-core
  - pydantic
  - torchaudio
  - numpy
  - structlog
  - torchmetrics
  - pip
  - pip:
    - omegaconf
    - ray[default]
    - soundfile
variables:
  DATA_ROOT: "/Users/kwatcharasupat/personal/data"