name: banda
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - pytorch
  - pytorch-lightning
  - hydra-core
  - pydantic
  - torchaudio
  - numpy
  - structlog
  - torchmetrics
  - soundfile
  - pip
  - pip:
    - omegaconf
    - ray[default]