name: banda
channels:
- pytorch
- nvidia
- conda-forge
dependencies:
- python=3.12
- pytorch
- pytorch-lightning
- hydra-core
- pydantic
- torchaudio
- numpy
- structlog
- torchmetrics
- pip
- pip:
  - omegaconf
  - ray[default]
  - soundfile
  - wandb

variables:
  DATA_ROOT: "~/Documents/data"
  HYDRA_FULL_ERROR: "1"
  PROJECT_ROOT: "~/Documents/projects/banda"
