version1:
  bands:
    - name: "V1"
      start_hz: 0
      end_hz: 20000
      bandwidth_hz: 20000
version2:
  bands:
    - name: "V1"
      start_hz: 0
      end_hz: 16000
      bandwidth_hz: 16000
    - name: "V2"
      start_hz: 16000
      end_hz: 20000
      bandwidth_hz: 4000
version3:
  bands:
    - name: "V1"
      start_hz: 0
      end_hz: 8000
      bandwidth_hz: 8000
    - name: "V2"
      start_hz: 8000
      end_hz: 16000
      bandwidth_hz: 8000
version4:
  bands:
    - name: "V1"
      start_hz: 0
      end_hz: 1000
      bandwidth_hz: 1000
    - name: "V2"
      start_hz: 1000
      end_hz: 8000
      bandwidth_hz: 7000
    - name: "V3"
      start_hz: 8000
      end_hz: 16000
      bandwidth_hz: 8000
version5:
  bands:
    - name: "V1"
      start_hz: 0
      end_hz: 1000
      bandwidth_hz: 1000
    - name: "V2"
      start_hz: 1000
      end_hz: 16000
      bandwidth_hz: 15000
    - name: "V3"
      start_hz: 16000
      end_hz: 20000
      bandwidth_hz: 4000
version6:
  bands:
    - name: "V1"
      start_hz: 0
      end_hz: 1000
      bandwidth_hz: 1000
    - name: "V2"
      start_hz: 1000
      end_hz: 4000
      bandwidth_hz: 3000
    - name: "V3"
      start_hz: 4000
      end_hz: 8000
      bandwidth_hz: 4000
    - name: "V4"
      start_hz: 8000
      end_hz: 16000
      bandwidth_hz: 8000
version7:
  bands:
    - name: "V1"
      start_hz: 0
      end_hz: 1000
      bandwidth_hz: 1000
    - name: "V2"
      start_hz: 1000
      end_hz: 4000
      bandwidth_hz: 3000
    - name: "V3"
      start_hz: 4000
      end_hz: 8000
      bandwidth_hz: 4000
    - name: "V4"
      start_hz: 8000
      end_hz: 16000
      bandwidth_hz: 8000
    - name: "V5"
      start_hz: 16000
      end_hz: 20000
      bandwidth_hz: 4000