_target_: banda.models.separator.Separator # This is the target for the overall separator model

stft_config:
  _target_: banda.models.common_components.spectral_components.spectral_base.STFTConfig
  n_fft: 2048
  hop_length: 512
  win_length: 2048
  window: hann # Corresponds to window_fn in original YAML
  center: true
  pad_mode: constant
  freeze_parameters: true # Default value, not in original YAML

bandsplit_module_config:
  _target_: banda.models.common_components.spectral_components.bandsplit.BandsplitModuleConfig
  n_bands: 1 # Assuming a default of 1 band if not specified, or needs to be derived
  emb_dim: 128 # From original YAML
  input_channels: 2 # From original YAML

mask_estimation_config:
  _target_: banda.models.common_components.mask_estimation.mask_estimation_modules.MaskEstimationConfig
  emb_dim: 128 # From original YAML
  output_channels: 2 # From original YAML

time_frequency_model_config:
  _target_: banda.models.common_components.time_frequency_models.tf_models.RNNTFModelConfig # Assuming RNN based on original tf_model_type
  n_modules: 12 # From original n_tf_modules
  emb_dim: 128 # From original YAML
  dropout: 0.0 # From original tf_dropout
  rnn_type: LSTM # From original YAML
  bidirectional: true # From original YAML
  rnn_dim: 256 # From original YAML
  max_seq_len_bands: null # Optional, setting to null
  max_seq_len_time: null # Optional, setting to null