_target_: banda.models.separator.Separator # This is the target for the overall separator model

stft_config:
  _target_: banda.models.common_components.spectral_components.spectral_base.STFTConfig
  n_fft: 2048
  hop_length: 512
  win_length: 2048
  window: hann
  center: true
  pad_mode: constant
  freeze_parameters: true

bandsplit_module_config:
  _target_: banda.models.common_components.spectral_components.bandsplit.BandsplitModuleConfig
  emb_dim: 128
  input_channels: 2

mask_estimation_config:
  _target_: banda.models.common_components.mask_estimation.mask_estimation_modules.MaskEstimationConfig
  emb_dim: 128
  output_channels: 2

time_frequency_model_config:
  _target_: banda.models.common_components.time_frequency_models.tf_models.RNNTFModelConfig
  n_modules: 8
  emb_dim: 128
  dropout: 0.0
  rnn_type: GRU
  bidirectional: true
  rnn_dim: 256
  max_seq_len_bands: null
  max_seq_len_time: null
