# Vocal Bandsplit Definitions
# Version 7
version7:
  bands:
    - start_hz: 0.0
      end_hz: 200.0
    - start_hz: 200.0
      end_hz: 400.0
    - start_hz: 400.0
      end_hz: 800.0
    - start_hz: 800.0
      end_hz: 1600.0
    - start_hz: 1600.0
      end_hz: 3200.0
    - start_hz: 3200.0
      end_hz: 6400.0
    - start_hz: 6400.0
      end_hz: null # To nyquist