# @package _global_

defaults:
  - data: default # Options: default, musdb18_sample
  - model: default
  - trainer: default
  - optimizer: default
  - loss: default
  - metrics: default
  - augmentations: default
  
  - override hydra/job_logging: default
  - override hydra/hydra_logging: default
  - _self_
  

# Project root directory
project_root: ${oc.env:PROJECT_ROOT,.}

# Experiment name
experiment_name: default_experiment

# Random seed for reproducibility
seed: 42

# Paths
paths:
  output_dir: ${hydra.run.dir}
  log_dir: ${hydra.run.dir}/logs
  data_dir: ${project_root}/data

# Hydra configuration
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}