# @package _global_

defaults:
  - _self_
  - model/stft: stft_config
  - model/bandsplit: bandsplit_musical_64
  - model/tfmodel: tfmodel_rnn_gru
  - model/mask_estim: mask_estim_default

model:
  _target_: banda.models.separator.Separator
  stems: ["vocals", "bass", "drums", "other"]
  fs: 44100
  emb_dim: 128
  in_channel: 2


# Project root directory
project_root: ${oc.env:PROJECT_ROOT,.}

# Experiment name
experiment_name: debug_run

# Random seed for reproducibility
seed: 42

# Set logging level to DEBUG
log_level: DEBUG

# Hydra configuration
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_debug
  job:
    chdir: False
  sweep:
    dir: multirun/${now:%Y-%m-%m}/${now:%H-%M-%S}_debug
    subdir: ${hydra.job.num}

# Paths
paths:
  output_dir: ${hydra.run.dir}
  log_dir: ${hydra.run.dir}/logs
  data_dir: ${project_root}/data

# Override specific configurations for this test run
data:
  target_: banda.data.datamodule.SourceSeparationDataModule
  batch_size: 1 # Reduced batch size
  num_workers: 0
  pin_memory: false
  train_dataset_config:
    target_: banda.data.datasets.musdb18hq.MUSDB18HQDataset
    config:
      split: train
      fs: 44100
      premix_transform:
        target_: banda.data.samplers.random_chunk.RandomChunkingTransform
        chunk_size_seconds: 1.0 # Reduced chunk size
        fs: 44100
      dataset_connector:
        target_: banda.data.datasets.musdb18hq.MUSDB18Connector
        config:
          split: train
          data_root: "${oc.env:DATA_ROOT}/musdb18hq/intermediates/npz"
  val_dataset_config:
    target_: banda.data.datasets.musdb18hq.MUSDB18HQDataset
    config:
      split: val
      fs: 44100
      premix_transform:
        target_: banda.data.samplers.random_chunk.RandomChunkingTransform
        chunk_size_seconds: 1.0 # Reduced chunk size
        fs: 44100
      dataset_connector:
        target_: banda.data.datasets.musdb18hq.MUSDB18Connector
        config:
          split: val
          data_root: "${oc.env:DATA_ROOT}/musdb18hq/intermediates/npz"
  test_dataset_config:
    target_: banda.data.datasets.musdb18hq.MUSDB18HQDataset
    config:
      split: test
      fs: 44100
      premix_transform:
        target_: banda.data.samplers.random_chunk.RandomChunkingTransform
        chunk_size_seconds: 1.0 # Reduced chunk size
        fs: 44100
      dataset_connector:
        target_: banda.data.datasets.musdb18hq.MUSDB18Connector
        config:
          split: test
          data_root: "${oc.env:DATA_ROOT}/musdb18hq/intermediates/npz"

trainer:
  target_: pytorch_lightning.Trainer
  max_epochs: 5 # Increased epochs
  accelerator: "auto"
  devices: "auto"
  log_every_n_steps: 1 # Log every step for debugging
  # Removed limit_train_batches, limit_val_batches, limit_test_batches

loss:
  target_: banda.losses.separation_loss_handler.SeparationLossHandler
  stft_loss_fn:
    _target_: banda.losses.multi_resolution_l1_snr.MultiResolutionSTFTLoss
    n_ffts: [2048, 512]
    hop_lengths: [512, 128]
    win_lengths: [2048, 512]
  time_loss_fn:
    _target_: banda.losses.time_domain_loss.TimeDomainLoss

metrics:
  _target_: torchmetrics.audio.ScaleInvariantSignalNoiseRatio
inference:
  chunk_size_seconds: 1.0 # Reduced chunk size for inference
  hop_size_seconds: 0.5   # Reduced hop size for inference
  fs: 44100
  batch_size: 1 # Reduced batch size for inference

optimizer:
  _target_: torch.optim.Adam
  lr: 0.001